apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-manager-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: group-manager-front
  template:
    metadata:
      labels:
        app: group-manager-front
    spec:

      containers:
      - name: group-manager-front
        image: ${CONTAINER_REGISTRY}/group-manager-front
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: group-manager-front
  name: group-manager-front
spec:
  ports:
  - port: 80
    nodePort: 31100
  selector:
    app: group-manager-front
  type: LoadBalancer
